# <center>Laboratorium 1<br>Metody Numeryczne</center>
Laboratorium 1 Metody Numeryczne<br>
Sprawozdanie <br>
***Michał Pogorzelec***

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [1]:
import main

import numpy as np
import scipy
from typing import List, Tuple, Union

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [2]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

***Rozwiązanie*** <br>
Skorzystałem z biblioteki math, by uzyskać liczbę PI oraz by móc zwrócić
wartość NaN.

In [1]:
import math

def cylinder_area(r: float, h: float) -> float:
    """Obliczenie pola powierzchni walca.

    Parameters:
    r (float): promień podstawy walca
    h (float): wysokosć walca

    Returns:
    float: pole powierzchni walca
    """
    if r < 0 or h < 0:
        return math.nan
    return (2 * math.pi * r * h) + (2 * math.pi * r**2)

***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

***Rozwiązanie*** <br>
Wypisuję dwa dowolne ciągi arytmetyczne o kroku różnym od jeden i nie będącym
liczbą całkowitą. Korzystam z funkcji arange() i linspace() dostępnych w bibliotece numpy.
Korzystając z funkcji arange() trzeba samodzielnie podać krok, ponieważ jego domyślna
wartość to 1. Natomiast funkcja linspace() wybiera krok randomowo i jest to liczba zmiennoprzecinkowa.

In [ ]:
fst_seq = np.arange(1, 10, 0.4)
print(fst_seq)
sec_seq = np.linspace(1, 10)
print(sec_seq)

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

***Rozwiązanie*** <br>
Uzupełniłem ciało funkcji tak, by zwracało wektor n pierwszych elementów
ciągu Fibbonnaciego. Skorzystałem z np.ndarray()

In [ ]:
def fib(n: int) -> Union[None, List[int], np.ndarray]:
    """Obliczenie pierwszych n wyrazów ciągu Fibonnaciego.

    Parameters:
    n (int): liczba określająca ilość wyrazów ciągu do obliczenia

    Returns:
    np.ndarray: wektor n pierwszych wyrazów ciągu Fibonnaciego.
    """

    if n <= 0 or type(n) is not int:
        return None
    result = [1, 1]
    if n == 1:
        return [1]
    for elem in range(0, n - 2):
        result += [result[-1] + result[-2]]

    return np.array([result])

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

***Rozwiązanie*** <br>
Funkcja która zwraca macierz odwrotną (lub NaN jeśli taka nie istnieje),
macierz transponowaną i wyznacznik macierzy. Skorzystałem tu z funkcji
(z bibliotek numpy oraz linalg) takich jak inv(), transpose() i det().

In [ ]:
def matrix_calculations(a: float) -> Tuple:
    """Funkcja zwraca wartości obliczeń na macierzy stworzonej
    na podstawie parametru a.

    Parameters:
    a (float): wartość liczbowa

    Returns:
    touple: krotka zawierająca wyniki obliczeń
    (Minv, Mt, Mdet) - opis parametrów w zadaniu 4.
    """

    M = np.array([[a, 1, -a], [0, 1, 1], [-a, a, 1]])
    Mdet = np.linalg.det(M)
    if Mdet == 0:
        Minv = math.nan
    else:
        Minv = np.linalg.inv(M)
    Mt = np.transpose(M)

    return Minv, Mt, Mdet

In [3]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie

***Rozwiązanie*** <br>
Po utworzeniu macierzy wypisuję jej poszczególne elementy, oraz definuję dwa
wektory w1 i w2.

In [ ]:
# [[3, 0, -2, 4], [1, 1, 1, 3], [-2, 1, 1, 0], [4, 5, 6, 1]]
M = np.array([[3, 0, -2, 4], [1, 1, 1, 3], [-2, 1, 1, 0], [4, 5, 6, 1]])
w1 = M[:, 2]
w2 = M[1, :]
print("Zadanie 5")
print("Macierz M:\n{0}".format(M))
print("Wektor w1:\n{0}".format(w1))
print("Wektor w2:\n{0}".format(w2))
print("Element [1,1]:\n{0}".format(M[0, 0]))
print("Element [3,3]:\n{0}".format(M[2, 2]))
print("Element [3,2]:\n{0}".format(M[2, 1]))
print("\n")

In [4]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

***Rozwiązanie*** <br>
Napisałem tak logikę funkcji by działała zgodnie z założeniami. Skorzystałem
z funkcji zeros(), do stworzenia macierzy zerowej, następnie każdy element zastępowałem
zgodnie z podanym algorytmem.

In [ ]:
def custom_matrix(m: int, n: int):
    """Funkcja zwraca macierz o wymiarze mxn zgodnie

    Parameters:
    m (int): ilość wierszy macierzy
    n (int): ilość kolumn macierzy

    Returns:
    np.ndarray: macierz zgodna z opisem z zadania 7.
    """
    if type(m) == float or type(n) == float:
        return None
    if m <= 0 or n <= 0:
        return None
    result = np.zeros((m, n))
    for row_ind in range(m):
        for col_ind in range(n):
            if row_ind > col_ind:
                result[row_ind][col_ind] = row_ind
            else:
                result[row_ind][col_ind] = col_ind
    return result
print(custom_matrix(4,6))

In [5]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

***Rozwiązanie*** <br>
Zdefiniowałem dwa wektory, następnie przeprowadziłem na nich parę operacji.
Przydatne okazały się funkcje multiply(), dot() oraz broadcasting typowy dla biblioteki numpy.

In [ ]:
v1 = np.array([1, 3, 13])
v2 = np.array([8, 5, -2])

result1 = np.multiply(4, v1)
# skorzystanie z własności broadcastingu
result2 = np.multiply(v2, -1) + 2
result3 = np.dot(v1, v2)
result4 = np.multiply(v1, v2)
print("Zadanie 7")
print(f"Result 1:\n{result1}")
print(f"Result 2:\n{result2}")
print(f"Result 3:\n{result3}")
print(f"Result 4:\n{result4}")

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

***Rozwiązanie*** <br>
Do poprzednich dwóch wektorów dołożyłem nową macierz na której również
przeprowadziłem parę operacji. Kluczowa była funkcja multiply(),
przydał się również broadcasting jak i funkcja transpose().

In [ ]:
M1 = np.array([[1, -7, 3], [-12, 3, 4], [5, 13, -3]])
result5 = np.multiply(M1, 3)
# skorzystanie z własności broadcastingu
result6 = M1 + 1
result7 = M1.transpose()
result8 = np.multiply(M1, v1)
result9 = np.multiply(v2.transpose(), M1)
print("Zadanie 8")
print(f"Result 5:\n{result5}")
print(f"Result 6:\n{result6}")
print(f"Result 7:\n{result7}")
print(f"Result 8:\n{result8}")
print(f"Result 9:\n{result9}")

***3. Wnioski***

Dzięki powyższym zadaniom nauczyłem się wykorzystywać bibliotekę numpy do
działań na macierzach i wektorach. Poznałem wiele ciekawych funkcji i właściwości,
takich jak chociażby broadcasting (termin ten polega na traktowaniu przez numpy macierzy o różnych wymiarach
podczas operacji arytmetycznych, np. dodając liczbę 1 do jakiejś macierzy,
numpy rozszerza tę liczbę do macierzy jedynkowej o wymiarach takich samych jak macierz do której dodajemy).
Przypomniałem sobie zasady type hintingu, oraz nauczyłem się korzystać z Jupytera.
Zapoznałem się także bliżej z dokumentacją biblioteki numpy.

P.S. <br>
Pliki jupyterowe na GitHubie nie działają w 100% poprawnie,
np. w moim sprawozdaniu nie widać tytułu na samej górze dokumentu.

Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)